#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1-0 -d 6 7 8 9 10

# Colors
bspc config focused_border_color \#89B4FA
bspc config normal_border_color \#7F849C

# Borders and gaps
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window rules
bspc rule -a firefox desktop='^2'

# Polybar
~/.config/polybar/launch.sh &
